name: Wakatime Stats Charts Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: dvjn/wakatime-charts@v0.3.1
            
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
